---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-volume
spec:
  capacity:
    storage: 5Gi      
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/wordpress-volume
    type: Directory      
